export enum OperationType {
  ADD,
  MODIFY,
  DELETE,
  UNLOCK,
  LOCK,
  ASSIGN_FUNCTION_FOR_PEOPLE,
  ACCEPT_PENDING,
  DECLINE_PENDING,
  SEND_EMAIL,
  APPLY,
  ASSIGN_ORGANIZATIONAL_UNIT,
  ASSIGN_FUNCTION,
  UPLOAD_LOGO
}
